=== gsautter/goldengate-server/files/server/Components/GgServerUDSData/FieldSets.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="fieldSets">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="fieldSet">
					<xs:annotation>
						<xs:documentation>a set of related data fields</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded">
							<xs:element name="field">
								<xs:annotation>
									<xs:documentation>an individual data field</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence minOccurs="0" maxOccurs="unbounded">
										<xs:element name="option">
											<xs:annotation>
												<xs:documentation>single option in a combo box. options present make a field a combo box automatically.</xs:documentation>
											</xs:annotation>
											<xs:complexType>
												<xs:attribute name="value" use="required">
													<xs:annotation>
														<xs:documentation>the option value</xs:documentation>
													</xs:annotation>
												</xs:attribute>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="name" use="required">
										<xs:annotation>
											<xs:documentation>name of the field, has to be unique in the field set</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="label" use="required">
										<xs:annotation>
											<xs:documentation>label to display next to the field</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="match">
										<xs:annotation>
											<xs:documentation>regular expression for validating input data. if not given, there is no validation</xs:documentation>
										</xs:annotation>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="name" use="required">
							<xs:annotation>
								<xs:documentation>name of the field set, has to be unique</xs:documentation>
							</xs:annotation>
						</xs:attribute>
						<xs:attribute name="label" use="required">
							<xs:annotation>
								<xs:documentation>label to display above the field set</xs:documentation>
							</xs:annotation>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== gsautter/goldengate-server/files/server/Components/GgServerUDSData/Fields.xml
<?xml version="1.0" encoding="UTF-8"?>
<fieldSets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="FieldSets.xsd">
	<fieldSet name="personal" label="Personal Information">
		<field label="Last Name" name="lastName"/>
		<field label="First Name" name="firstName"/>
		<field label="Gender" name="gender">
			<option value="Female"/>
			<option value="Male"/>
		</field>
		<field label="Date of Birth (DD-MM-YYYY)" name="birthday" match="[0-9]++[\/\-\s\.][0-9]++[\/\-\s\.][0-9]++"/>
	</fieldSet>
	<fieldSet name="contact" label="Contact Information">
		<field label="eMail Address" name="eMail" match="[^\@\s]++\@[^\@\s]++"/>
		<field label="Skype Name" name="skype"/>
	</fieldSet>
</fieldSets>
